export const lang = {
    required: "This field is required",
    email: "This field requires a valid e-mail address",
    number: "This field requires a number",
    integer: "This field requires an integer number",
    url: "This field requires a valid website URL",
    tel: "This field requires a valid telephone number",
    maxlength: "This fields length must be < ${1}",
    minlength: "This fields length must be > ${1}",
    min: "Minimum value for this field is ${1}",
    max: "Maximum value for this field is ${1}",
    pattern: "Input must match the pattern ${1}",
    zipcode: "This field requires a valid ZIP code",
    pwdmatch: "The two passwords don't match",
    minage: "The user must be at least ${1} years old",
    validate: "Condition not satisfied: ${1}",
};
